version: '3.8'

services:
  redis:
    build: ./redis
    restart: always
  worker:
    build:
      context: .
      dockerfile: ./worker/Dockerfile
  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    volumes:
      - ./server:/app/server
    ports:
      - '8080:8080'
  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    volumes:
      - ./client:/app/client
    ports:
      - '5173:5173'
